include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/_deprecated/**"
    - "lib/test_app.dart"
    - "lib/main_simple_working.dart"
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
