name: companion_app
description: 医小伴陪诊师端应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 网络请求
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # 状态管理
  provider: ^6.1.2
  
  # 工具类
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  
  # 最小化资源
  assets:
    - assets/placeholder/
